version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'
  busTracker:
    depends_on:
      - postgres
    build:
      context: docker
      dockerfile: Dockerfile
    image: bus
    restart: always
    ports:
      - "8080:8080"
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/postgres'
      - 'DB_USER=postgres'
      - 'DB_PASSWORD=postgres'